version: '3.8'
services:
  cassandra:
    image: cassandra
    ports:
      - '9042:9042'

  mysql:
    image: mysql:5.6.30
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: microserviceapp
    ports:
      - '3306:3306'

  elasticsearch:
    image: elasticsearch:6.8.5
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node

