version: '3.8'
services:
  cassandra:
    image: cassandra
    ports:
      - '9042:9042'

  mysql:
    image: mysql:5.6.30
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: microserviceapp
    ports:
      - '3306:3306'

  elasticsearch:
    image: elasticsearch:8.12.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      xpack.security.enabled: false
      xpack.security.enrollment.enabled: false
      discovery.type: single-node

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user

  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user
      - MONGO_INITDB_DATABASE=user



